#pragma once
#include <windows.h>
#include <unknwn.h>
#include <restrictederrorinfo.h>
#include <hstring.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.ApplicationModel.Activation.h>
#include <winrt/Windows.UI.Xaml.h>
#include <winrt/Windows.UI.Xaml.Controls.h>
#include <winrt/Windows.UI.Xaml.Controls.Primitives.h>
#include <winrt/Windows.UI.Xaml.Data.h>
#include <winrt/Windows.UI.Xaml.Interop.h>
#include <winrt/Windows.UI.Xaml.Markup.h>
#include <winrt/Windows.UI.Xaml.Navigation.h>
#include <winrt/Windows.UI.Xaml.Shapes.h>
#include <winrt/Windows.UI.Xaml.Media.h>

#include <winrt/Windows.Storage.h>
#include <winrt/Windows.Media.h>
#include <winrt/Windows.Media.Audio.h>
#include <winrt/Windows.Media.Capture.h>
#include <winrt/Windows.UI.h>
#include <winrt/Windows.UI.Core.h>
#include <winrt/WIndows.Devices.Enumeration.h>
#include <winrt/Windows.Media.MediaProperties.h>

#include <algorithm>
#include <thread>
#include <chrono>
#include <vector>
#include <list>
#include <complex>
#include <iterator>
#include <string>
#include <cmath>
#include <limits>
#include <functional>
#include <cstdlib>
#include <mutex>
#include <atomic>
#include <queue>
#include <map>
#include <future>
#include <type_traits>
#include <sstream>
#include <execution>
#include "fftw3.h"